---
abstract: 'Build complex selectors as a single sub'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  Pod::Elemental::Element::Generic::Blank: 0
  Pod::Elemental::Element::Generic::Command: 0
  Pod::Elemental::Element::Pod5::Command: 0
  Pod::Elemental::Element::Pod5::Ordinary: 0
  Pod::Elemental::Element::Pod5::Region: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Elemental-MakeSelector
requires:
  Carp: 0
  Pod::Elemental: 0.102360
  Sub::Exporter: 0
  if: 0
  perl: 5.010_001
resources:
  repository: git://github.com/madsen/pod-elemental-makeselector.git
version: 0.03
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: CJM/VersionFromModule
      version: 0.08
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: CJM/GatherDir
      version: 5.009
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: CJM/PruneCruft
      version: 5.009
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: CJM/ManifestSkip
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: CJM/MetaJSON
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: CJM/MetaYAML
      version: 5.009
    -
      class: Dist::Zilla::Plugin::License
      name: CJM/License
      version: 5.009
    -
      class: Dist::Zilla::Plugin::Test::PrereqsFromMeta
      name: CJM/Test::PrereqsFromMeta
      version: 4.21
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: CJM/PodSyntaxTests
      version: 5.009
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: CJM/PodCoverageTests
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: CJM/MakeMaker
      version: 5.009
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: CJM/RunExtraTests
      version: 0.011
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: CJM/MetaConfig
      version: 5.009
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: CJM/MatchManifest
      version: 4.01
    -
      class: Dist::Zilla::Plugin::RecommendedPrereqs
      name: CJM/RecommendedPrereqs
      version: 4.21
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CJM/CheckPrereqsIndexed
      version: 0.009
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: CJM/GitVersionCheckCJM
      version: 4.13
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: CJM/TemplateCJM
      version: 4.21
    -
      class: Dist::Zilla::Plugin::Repository
      name: CJM/Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: CJM/@Git/Check
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: CJM/@Git/Commit
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: CJM/@Git/Tag
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: CJM/@Git/Push
      version: 2.017
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: CJM/TestRelease
      version: 5.009
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: CJM/UploadToCPAN
      version: 5.009
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: CJM/ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::Transformer
              name: Lists
              version: 4.005
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: 4.005
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: CRITERIA
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: SUBROUTINES
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: EXTENDING
              version: 4.005
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: 4.005
            -
              class: Pod::Weaver::Section::BugsRT
              name: BugsRT
              version: 0.52
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: 4.005
            -
              class: Pod::Weaver::Section::SourceGitHub
              name: SourceGitHub
              version: 0.54
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: 4.005
            -
              class: Pod::Weaver::Plugin::EnsureUniqueSections
              name: '-EnsureUniqueSections'
              version: 0.121550
      name: PodWeaver
      version: 4.002
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.009
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.009
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.009
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.009
